add Tests
Bob-short-for-Robert/pm4-bob pull request #17
Opened 2022-05-06 16:41 UTC by SomethingWittyWithATechAspect

Test for Start menu are not running - dont know if they worked beforehand

walls don't seem to be fixed - Collsion Test are failing

2022-05-06 16:51 UTC, SomethingWittyWithATechAspect commented
also didnt found where menutest is, menu test is most likely in the wrong dir
expect im blind

2022-05-07 08:23 UTC, spirit126 requested changes

2022-05-07 08:23 UTC, spirit126 commented on Assets/Editor/Tests/CameraTest.cs
> +}
no newline at end of file

2022-05-07 08:23 UTC, spirit126 commented on Assets/Editor/Tests/CollisionTest.cs
> +}
no newline

2022-05-07 08:23 UTC, spirit126 commented on Assets/Editor/Tests/ShooterTest.cs
> +        }
why not use Assert.Equals

2022-05-07 08:23 UTC, spirit126 commented on Assets/Editor/Tests/ShooterTest.cs
> +        Assert.IsTrue(2.Equals( altUnityDriver.FindObjects(By.TAG, "Projectile").Count));
why not use Assert.Equals

2022-05-07 08:23 UTC, spirit126 commented on Assets/Editor/Tests/ShooterTest.cs
> +}
no newline

2022-05-07 08:23 UTC, spirit126 commented on Assets/Editor/Tests/CameraTest.cs
> +    private string SceneName = "Main";
altUnityDriver -> _altUnityDriver, and can be made readonly
SceneName: naming convention and can be made constant

2022-05-07 08:23 UTC, spirit126 commented on Assets/Editor/Tests/CollisionTest.cs
> +
same as above

2022-05-07 08:23 UTC, spirit126 commented on Assets/Editor/Tests/ShooterTest.cs
> +
same as above

2022-05-07 08:29 UTC, spirit126 commented
- Player Prefab is outdated (the new version is in the Main Scene)
- The New Game button does not work anymore

2022-05-12 06:29 UTC, SomethingWittyWithATechAspect commented
> * Player Prefab is outdated (the new version is in the Main Scene)
> * The New Game button does not work anymore

done
done

2022-05-12 06:41 UTC, spirit126 approved these changes
tested, fine now

2022-05-12 06:51 UTC, merged